-- Catalogo de infracoes: pontos e valor-base por codigo, para auto-preencher
-- o formulario e complementar a leitura automatica de PDF (que nao traz
-- pontos). Semeado a partir do historico real de multas ja recebidas
-- (planilha CONTROLE MULTAS), nao de tabela generica - cobre os codigos que
-- a frota realmente recebeu. Valor e sempre editavel (pode ter juros/
-- correcao no boleto real); pontos e fixo por infracao.

CREATE TABLE IF NOT EXISTS infraction_catalog (
  code TEXT PRIMARY KEY,
  description TEXT NOT NULL,
  points INTEGER NOT NULL,
  base_amount_cents INTEGER,
  source TEXT NOT NULL DEFAULT 'historico_planilha',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO infraction_catalog (code, description, points, base_amount_cents) VALUES
  ('675-0', 'FALTA DE INDICACAO TARA/PBT', 0, 13016),
  ('5002', 'NAO IDENTIFICACAO DO CONDUTOR INFRATOR, IMPOSTA A PJ (2a MULTA)', 0, 26032),
  ('5053', 'DIRIGIR VEICULO SEM UTILIZAR LENTES CORRETORAS DE VISAO', 7, 29347),
  ('5185', 'DEIXAR O CONDUTOR DE USAR O CINTO DE SEGURANCA', 5, 19523),
  ('5541-2', 'ESTACIONAR EM DESACORDO COM A REGULAMENTACAO - ESTACIONAMENTO ROTATIVO', 5, 19523),
  ('5681', 'TRANSITAR NA FAIXA OU PISTA DA DIREITA', 3, 9280),
  ('5703', 'DEIXAR DE CONSERVAR O VEICULO NA FAIXA A ELE DESTINADA PELA SINALIZACAO DE REGULAMENTACAO', 4, 13016),
  ('5746-1', 'TRANSITAR EM LOCAL/HORARIO NAO PERMITIDO PELA REGULAMENTACAO ESTABELECIDA', 4, 13016),
  ('5746-2', 'TRANSITAR EM LOCAL/HORARIO NAO PERMITIDO PELA REGULAMENTACAO - RODIZIO', 4, 13016),
  ('5770', 'NAO DAR PASSAGEM A VEICULO DE POLICIA EM SERVICO DE URGENCIA DEVIDAMENTE IDENTIFICADO', 7, 29347),
  ('5851-1', 'DEIXAR DE DESLOCAR COM ANTECEDENCIA O VEICULO PARA FAIXA MAIS A ESQUERDA QUANDO FOR MANOBRAR', 4, 13016),
  ('5967-0', 'ULTRAPASSAR PELA CONTRAMAO LINHA DE DIVISAO DE FLUXOS OPOSTOS CONTINUA AMARELA', 7, 146735),
  ('6041-2', 'EXECUTAR OPERACAO DE CONVERSAO A ESQUERDA EM LOCAL PROIBIDO PELA SINALIZACAO', 5, 19523),
  ('6050', 'AVANCAR SINAL DE PARADA OBRIGATORIA', 7, 29347),
  ('6050-3', 'AVANCAR SINAL VERMELHO DO SEMAFORO', 7, 29347),
  ('6068', 'NAO ENTRAR EM BALANCA PARA PESAGEM DO VEICULO', 5, 19523),
  ('6068-2', 'DEIXAR DE ADENTRAR AS AREAS DESTINADAS A PESAGEM DE VEICULOS', 5, 19523),
  ('6270', 'NAO REDUZIR A VELOCIDADE ONDE O TRANSITO ESTEJA SENDO CONTROLADO PELO AGENTE', 5, 19523),
  ('6670', 'CONDUZIR O VEICULO COM EQUIPAMENTO DO SISTEMA DE ILUMINACAO ALTERADO', 5, 19523),
  ('6726', 'CONDUZIR VEICULO EM MAU ESTADO DE CONSERVACAO, COMPROMETENDO A SEGURANCA', 5, 19523),
  ('6769-0', 'CONDUZIR VEICULO COM DEFEITO NO SISTEMA DE ILUMINACAO, SINALIZACAO OU LAMPADAS QUEIMADAS', 4, 13016),
  ('6920', 'NAO EFETUAR REGISTRO DO VEICULO EM 30 DIAS, QUANDO FOR TRANSFERIDA A PROPRIEDADE', 0, 13016),
  ('7366', 'DIRIGIR VEICULO UTILIZANDO CELULAR', 4, 13016),
  ('7455-0', 'TRANSITAR EM VELOCIDADE SUPERIOR A MAXIMA PERMITIDA EM ATE 20%', 4, 13016),
  ('7463', 'TRANSITAR EM VELOCIDADE SUPERIOR A MAXIMA PERMITIDA ACIMA DE 20% ATE 50%', 5, 19523),
  ('7471', 'TRANSITAR EM VELOCIDADE SUPERIOR A MAXIMA PERMITIDA ACIMA DE 50%', 7, 88041),
  ('7633-2', 'DIRIGIR O VEICULO MANUSEANDO TELEFONE CELULAR', 7, 29347),
  ('7722', 'DEIXAR DE MANTER ACESA A LUZ BAIXA DO VEICULO DURANTE O DIA EM RODOVIAS', 4, 13016)
ON CONFLICT (code) DO NOTHING;
